services:
  portfolio-cms:
    image: ghcr.io/trinhxuantam/portfolio-cms:latest
    env_file: .env
    ports:
      - "1337:1337"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    name: portfolio-network
