name: publish

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: trinhxuantam/portfolio-crm:latest


jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: |
        echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u trinhxuantam --password-stdin

    - name: Build and publish Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: connect and pull
      run: |
        scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
          cd ${{ secrets.WORK_DIR }} && \
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u trinhxuantam --password-stdin && \
          docker-compose pull && \
          docker-compose up -d && \
        exit"

    - name: cleanup
      run: rm -rf ~/.ssh
